// Generated by gencpp from file sentinel_drone_driver/CommandBool.msg
// DO NOT EDIT!


#ifndef SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOL_H
#define SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOL_H

#include <ros/service_traits.h>


#include <sentinel_drone_driver/CommandBoolRequest.h>
#include <sentinel_drone_driver/CommandBoolResponse.h>


namespace sentinel_drone_driver
{

struct CommandBool
{

typedef CommandBoolRequest Request;
typedef CommandBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandBool
} // namespace sentinel_drone_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sentinel_drone_driver::CommandBool > {
  static const char* value()
  {
    return "e09abbb4e5bae6b558e5010966eb6e9e";
  }

  static const char* value(const ::sentinel_drone_driver::CommandBool&) { return value(); }
};

template<>
struct DataType< ::sentinel_drone_driver::CommandBool > {
  static const char* value()
  {
    return "sentinel_drone_driver/CommandBool";
  }

  static const char* value(const ::sentinel_drone_driver::CommandBool&) { return value(); }
};


// service_traits::MD5Sum< ::sentinel_drone_driver::CommandBoolRequest> should match
// service_traits::MD5Sum< ::sentinel_drone_driver::CommandBool >
template<>
struct MD5Sum< ::sentinel_drone_driver::CommandBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sentinel_drone_driver::CommandBool >::value();
  }
  static const char* value(const ::sentinel_drone_driver::CommandBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentinel_drone_driver::CommandBoolRequest> should match
// service_traits::DataType< ::sentinel_drone_driver::CommandBool >
template<>
struct DataType< ::sentinel_drone_driver::CommandBoolRequest>
{
  static const char* value()
  {
    return DataType< ::sentinel_drone_driver::CommandBool >::value();
  }
  static const char* value(const ::sentinel_drone_driver::CommandBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sentinel_drone_driver::CommandBoolResponse> should match
// service_traits::MD5Sum< ::sentinel_drone_driver::CommandBool >
template<>
struct MD5Sum< ::sentinel_drone_driver::CommandBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sentinel_drone_driver::CommandBool >::value();
  }
  static const char* value(const ::sentinel_drone_driver::CommandBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sentinel_drone_driver::CommandBoolResponse> should match
// service_traits::DataType< ::sentinel_drone_driver::CommandBool >
template<>
struct DataType< ::sentinel_drone_driver::CommandBoolResponse>
{
  static const char* value()
  {
    return DataType< ::sentinel_drone_driver::CommandBool >::value();
  }
  static const char* value(const ::sentinel_drone_driver::CommandBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOL_H
