// Generated by gencpp from file sentinel_drone_driver/CommandBoolRequest.msg
// DO NOT EDIT!


#ifndef SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOLREQUEST_H
#define SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sentinel_drone_driver
{
template <class ContainerAllocator>
struct CommandBoolRequest_
{
  typedef CommandBoolRequest_<ContainerAllocator> Type;

  CommandBoolRequest_()
    : value(false)  {
    }
  CommandBoolRequest_(const ContainerAllocator& _alloc)
    : value(false)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CommandBoolRequest_

typedef ::sentinel_drone_driver::CommandBoolRequest_<std::allocator<void> > CommandBoolRequest;

typedef boost::shared_ptr< ::sentinel_drone_driver::CommandBoolRequest > CommandBoolRequestPtr;
typedef boost::shared_ptr< ::sentinel_drone_driver::CommandBoolRequest const> CommandBoolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator1> & lhs, const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator1> & lhs, const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sentinel_drone_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e431d687bf4b2c65fbd94b12ae0cb5d9";
  }

  static const char* value(const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe431d687bf4b2c65ULL;
  static const uint64_t static_value2 = 0xfbd94b12ae0cb5d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentinel_drone_driver/CommandBoolRequest";
  }

  static const char* value(const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Common type for switch commands\n"
"\n"
"bool value\n"
;
  }

  static const char* value(const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandBoolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentinel_drone_driver::CommandBoolRequest_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOLREQUEST_H
