// Generated by gencpp from file sentinel_drone_driver/CommandBoolResponse.msg
// DO NOT EDIT!


#ifndef SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOLRESPONSE_H
#define SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sentinel_drone_driver
{
template <class ContainerAllocator>
struct CommandBoolResponse_
{
  typedef CommandBoolResponse_<ContainerAllocator> Type;

  CommandBoolResponse_()
    : success(false)
    , result(0)  {
    }
  CommandBoolResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandBoolResponse_

typedef ::sentinel_drone_driver::CommandBoolResponse_<std::allocator<void> > CommandBoolResponse;

typedef boost::shared_ptr< ::sentinel_drone_driver::CommandBoolResponse > CommandBoolResponsePtr;
typedef boost::shared_ptr< ::sentinel_drone_driver::CommandBoolResponse const> CommandBoolResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator1> & lhs, const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator1> & lhs, const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sentinel_drone_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cd894375e4e3d2861d2222772894fdb";
  }

  static const char* value(const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cd894375e4e3d28ULL;
  static const uint64_t static_value2 = 0x61d2222772894fdbULL;
};

template<class ContainerAllocator>
struct DataType< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentinel_drone_driver/CommandBoolResponse";
  }

  static const char* value(const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"uint8 result\n"
"\n"
"\n"
;
  }

  static const char* value(const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandBoolResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentinel_drone_driver::CommandBoolResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTINEL_DRONE_DRIVER_MESSAGE_COMMANDBOOLRESPONSE_H
