// Generated by gencpp from file sentinel_drone_driver/PIDError.msg
// DO NOT EDIT!


#ifndef SENTINEL_DRONE_DRIVER_MESSAGE_PIDERROR_H
#define SENTINEL_DRONE_DRIVER_MESSAGE_PIDERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sentinel_drone_driver
{
template <class ContainerAllocator>
struct PIDError_
{
  typedef PIDError_<ContainerAllocator> Type;

  PIDError_()
    : roll_error(0.0)
    , pitch_error(0.0)
    , throttle_error(0.0)
    , yaw_error(0.0)
    , zero_error(0.0)  {
    }
  PIDError_(const ContainerAllocator& _alloc)
    : roll_error(0.0)
    , pitch_error(0.0)
    , throttle_error(0.0)
    , yaw_error(0.0)
    , zero_error(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_error_type;
  _roll_error_type roll_error;

   typedef float _pitch_error_type;
  _pitch_error_type pitch_error;

   typedef float _throttle_error_type;
  _throttle_error_type throttle_error;

   typedef float _yaw_error_type;
  _yaw_error_type yaw_error;

   typedef float _zero_error_type;
  _zero_error_type zero_error;





  typedef boost::shared_ptr< ::sentinel_drone_driver::PIDError_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentinel_drone_driver::PIDError_<ContainerAllocator> const> ConstPtr;

}; // struct PIDError_

typedef ::sentinel_drone_driver::PIDError_<std::allocator<void> > PIDError;

typedef boost::shared_ptr< ::sentinel_drone_driver::PIDError > PIDErrorPtr;
typedef boost::shared_ptr< ::sentinel_drone_driver::PIDError const> PIDErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentinel_drone_driver::PIDError_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sentinel_drone_driver::PIDError_<ContainerAllocator1> & lhs, const ::sentinel_drone_driver::PIDError_<ContainerAllocator2> & rhs)
{
  return lhs.roll_error == rhs.roll_error &&
    lhs.pitch_error == rhs.pitch_error &&
    lhs.throttle_error == rhs.throttle_error &&
    lhs.yaw_error == rhs.yaw_error &&
    lhs.zero_error == rhs.zero_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sentinel_drone_driver::PIDError_<ContainerAllocator1> & lhs, const ::sentinel_drone_driver::PIDError_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sentinel_drone_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone_driver::PIDError_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone_driver::PIDError_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone_driver::PIDError_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "965f4467327ee9171cf551616b23b064";
  }

  static const char* value(const ::sentinel_drone_driver::PIDError_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x965f4467327ee917ULL;
  static const uint64_t static_value2 = 0x1cf551616b23b064ULL;
};

template<class ContainerAllocator>
struct DataType< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentinel_drone_driver/PIDError";
  }

  static const char* value(const ::sentinel_drone_driver::PIDError_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float32 roll_error\n"
"float32 pitch_error\n"
"float32 throttle_error\n"
"float32 yaw_error\n"
"\n"
"float32 zero_error\n"
"\n"
;
  }

  static const char* value(const ::sentinel_drone_driver::PIDError_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll_error);
      stream.next(m.pitch_error);
      stream.next(m.throttle_error);
      stream.next(m.yaw_error);
      stream.next(m.zero_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDError_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentinel_drone_driver::PIDError_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentinel_drone_driver::PIDError_<ContainerAllocator>& v)
  {
    s << indent << "roll_error: ";
    Printer<float>::stream(s, indent + "  ", v.roll_error);
    s << indent << "pitch_error: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_error);
    s << indent << "throttle_error: ";
    Printer<float>::stream(s, indent + "  ", v.throttle_error);
    s << indent << "yaw_error: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_error);
    s << indent << "zero_error: ";
    Printer<float>::stream(s, indent + "  ", v.zero_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTINEL_DRONE_DRIVER_MESSAGE_PIDERROR_H
