// Generated by gencpp from file sentinel_drone_driver/RCMessage.msg
// DO NOT EDIT!


#ifndef SENTINEL_DRONE_DRIVER_MESSAGE_RCMESSAGE_H
#define SENTINEL_DRONE_DRIVER_MESSAGE_RCMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sentinel_drone_driver
{
template <class ContainerAllocator>
struct RCMessage_
{
  typedef RCMessage_<ContainerAllocator> Type;

  RCMessage_()
    : rc_throttle(0)
    , rc_roll(0)
    , rc_pitch(0)
    , rc_yaw(0)  {
    }
  RCMessage_(const ContainerAllocator& _alloc)
    : rc_throttle(0)
    , rc_roll(0)
    , rc_pitch(0)
    , rc_yaw(0)  {
  (void)_alloc;
    }



   typedef uint16_t _rc_throttle_type;
  _rc_throttle_type rc_throttle;

   typedef uint16_t _rc_roll_type;
  _rc_roll_type rc_roll;

   typedef uint16_t _rc_pitch_type;
  _rc_pitch_type rc_pitch;

   typedef uint16_t _rc_yaw_type;
  _rc_yaw_type rc_yaw;





  typedef boost::shared_ptr< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> const> ConstPtr;

}; // struct RCMessage_

typedef ::sentinel_drone_driver::RCMessage_<std::allocator<void> > RCMessage;

typedef boost::shared_ptr< ::sentinel_drone_driver::RCMessage > RCMessagePtr;
typedef boost::shared_ptr< ::sentinel_drone_driver::RCMessage const> RCMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sentinel_drone_driver::RCMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sentinel_drone_driver::RCMessage_<ContainerAllocator1> & lhs, const ::sentinel_drone_driver::RCMessage_<ContainerAllocator2> & rhs)
{
  return lhs.rc_throttle == rhs.rc_throttle &&
    lhs.rc_roll == rhs.rc_roll &&
    lhs.rc_pitch == rhs.rc_pitch &&
    lhs.rc_yaw == rhs.rc_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sentinel_drone_driver::RCMessage_<ContainerAllocator1> & lhs, const ::sentinel_drone_driver::RCMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sentinel_drone_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41f534868ff2103b914923c89e4aa7e5";
  }

  static const char* value(const ::sentinel_drone_driver::RCMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41f534868ff2103bULL;
  static const uint64_t static_value2 = 0x914923c89e4aa7e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sentinel_drone_driver/RCMessage";
  }

  static const char* value(const ::sentinel_drone_driver::RCMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint16 rc_throttle\n"
"uint16 rc_roll\n"
"uint16 rc_pitch\n"
"uint16 rc_yaw\n"
"\n"
;
  }

  static const char* value(const ::sentinel_drone_driver::RCMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rc_throttle);
      stream.next(m.rc_roll);
      stream.next(m.rc_pitch);
      stream.next(m.rc_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RCMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sentinel_drone_driver::RCMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sentinel_drone_driver::RCMessage_<ContainerAllocator>& v)
  {
    s << indent << "rc_throttle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rc_throttle);
    s << indent << "rc_roll: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rc_roll);
    s << indent << "rc_pitch: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rc_pitch);
    s << indent << "rc_yaw: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rc_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENTINEL_DRONE_DRIVER_MESSAGE_RCMESSAGE_H
