# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sentinel_drone_driver/PIDError.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PIDError(genpy.Message):
  _md5sum = "965f4467327ee9171cf551616b23b064"
  _type = "sentinel_drone_driver/PIDError"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
float32 roll_error
float32 pitch_error
float32 throttle_error
float32 yaw_error

float32 zero_error

"""
  __slots__ = ['roll_error','pitch_error','throttle_error','yaw_error','zero_error']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       roll_error,pitch_error,throttle_error,yaw_error,zero_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PIDError, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.roll_error is None:
        self.roll_error = 0.
      if self.pitch_error is None:
        self.pitch_error = 0.
      if self.throttle_error is None:
        self.throttle_error = 0.
      if self.yaw_error is None:
        self.yaw_error = 0.
      if self.zero_error is None:
        self.zero_error = 0.
    else:
      self.roll_error = 0.
      self.pitch_error = 0.
      self.throttle_error = 0.
      self.yaw_error = 0.
      self.zero_error = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.roll_error, _x.pitch_error, _x.throttle_error, _x.yaw_error, _x.zero_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.roll_error, _x.pitch_error, _x.throttle_error, _x.yaw_error, _x.zero_error,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.roll_error, _x.pitch_error, _x.throttle_error, _x.yaw_error, _x.zero_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.roll_error, _x.pitch_error, _x.throttle_error, _x.yaw_error, _x.zero_error,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
